apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-restart-configure-ovs
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            compression: gzip
            source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCiNUaGUgaW50ZXJmYWNlIG5hbWUgaXMgcGFzc2VkIGFzIHRoZSBmaXJzdCBhcmd1bWVudCAoJDEpCiNUaGUgYWN0aW9uIGlzIHBhc3NlZCBhcyB0aGUgc2Vjb25kIGFyZ3VtZW50ICgkMikKCiNEZWZpbmUgdGhlIGludGVyZmFjZSBhbmQgc2VydmljZSB3ZSBjYXJlIGFib3V0ClRBUkdFVF9JTlRFUkZBQ0U9ImJyLWV4IgpTRVJWSUNFX1RPX1JFU1RBUlQ9Im92cy1jb25maWd1cmF0aW9uLnNlcnZpY2UiCgojQ2hlY2sgaWYgdGhlIGV2ZW50IGlzIGZvciBvdXIgdGFyZ2V0IGludGVyZmFjZSBhbmQgdGhlIGFjdGlvbiBpcyAndXAnIG9yICdkaGNwNC1jaGFuZ2UnCmlmIFtbICIkMSIgPT0gIiR7VEFSR0VUX0lOVEVSRkFDRX0iICYmICggIiQyIiA9PSAidXAiIHx8ICIkMiIgPT0gImRoY3A0LWNoYW5nZSIgKSBdXTsgdGhlbgogICAgIyBpTG9nIHRoZSBhY3Rpb24gZm9yIGRlYnVnZ2luZyBwdXJwb3NlcwogICAgbG9nZ2VyICJOZXR3b3JrTWFuYWdlciBEaXNwYXRjaGVyOiBJUCBhc3NpZ25lZCB0byAke1RBUkdFVF9JTlRFUkZBQ0V9LCByZXN0YXJ0aW5nICR7U0VSVklDRV9UT19SRVNUQVJUfS4iCgogICAgaWYgc3lzdGVtY3RsIGlzLWFjdGl2ZSAtLXF1aWV0ICIke1NFUlZJQ0VfVE9fUkVTVEFSVH0iCiAgICAjIFJlc3RhcnQgdGhlIGRlc2lyZWQgc2VydmljZQogICAgICAgc3lzdGVtY3RsIHJlc3RhcnQgJHtTRVJWSUNFX1RPX1JFU1RBUlR9CiAgICBmaQpmaQo=
          mode: 0755
          overwrite: true
          path: /etc/NetworkManager/dispatcher.d/99-restart-ovs-config-service.sh
